# -*- coding: utf-8 -*-
"""OAuth_Flows.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TAcF7Y8W7hAmXonoHMbrTyvrMvYm5vN2
"""

!pip install requests
!pip install IPython

import requests
from IPython.display import HTML

# Define Salesforce OAuth details
client_id = '3MVG9Y6d_Btp4xp6axNHLOn5pGKI_LiwnGBehM.gxmlXeannCcTQHBSh_5gwp2oJ7oIltK1XT5qm.iKHqfHUN'
client_secret = 'YOUR_CLIENT_SECRET'
redirect_uri = 'YOUR_REDIRECT_URI'
authorization_url = 'https://login.salesforce.com/services/oauth2/authorize'

# Step 1: Get the Authorization Code (User Interaction Required)
auth_params = {
    'response_type': 'code',
    'client_id': client_id,
    'redirect_uri': 'https://www.getpostman.com/oauth2/callback',
    'scope': 'full'
}

auth_url = f"{authorization_url}?{'&'.join([f'{k}={v}' for k, v in auth_params.items()])}"

HTML(f'<a href="{auth_url}" target="_blank">Click here to authorize</a>')

# In a real browser, this link would open a Salesforce login page and
# request authorization. However, it's challenging to capture the response in Colab.

# Step 2: Handle the Callback and Exchange Authorization Code for Access Token
# Since handling the callback in Colab is not straightforward, you might need to do this manually in a local environment.

# You'd typically make an HTTP POST request to Salesforce's token endpoint
# to exchange the authorization code for an access token.